# -*- coding: utf-8 -*-
"""pracIR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hx79MKxz7gv3S3x2iym_Uiry83AZF5tA
"""

import cv2
import matplotlib.pyplot as plt
from skimage.color import rgb2gray

import cv2
import matplotlib.pyplot as plt

# Read the image
img = cv2.imread("cat.jpg")

# Check if the image was read successfully
if img is None:
    print("Error: Unable to read the image file")
else:
    # Display the image
    plt.imshow(img)
    plt.show()

red, yellow = img.copy(), img.copy()
red[:, :, (1,2)] = 0
yellow[:, :, 2] = 0
f = plt.figure()
f.add_subplot(1,2, 1)
plt.imshow(red)
f.add_subplot(1,2, 2)
plt.imshow(yellow)
plt.show(block=True)

f = plt.figure()
f.add_subplot(1,2, 1)
plt.imshow(img)
f.add_subplot(1,2, 2)
plt.imshow(rgb2gray(img))
plt.show(block=True)

gimg = cv2.GaussianBlur(img,(105,105),cv2.BORDER_DEFAULT)
f = plt.figure()
f.add_subplot(1,2, 1)
plt.imshow(img)
f.add_subplot(1,2, 2)
plt.imshow(gimg)
plt.show(block=True)

histg = cv2.calcHist([img],[0],None,[256],[0,256])
plt.plot(histg)





